### ISSUE TITLE
Regression: Trace id not correctly propagated between calls. 

### ISSUE THREAD

**Issue by jdbennet2001** [census-instrumentation/opencensus-node#566] opened 2019-05-30 20:30 UTC
Please answer these questions before submitting a bug report.

### What version of OpenCensus are you using?
0.0.13

### What version of Node are you using?
8.112.0 (Mac)

### What did you do?
I have a node micro-service that is instrumented using Open Census. 

I have legacy code that invokes the service using:

```
curl --request POST \
  --url http://localhost:3971/datalayer/graphql \
  --header 'accept: application/json' \
  --header 'authorization: removed' \
  --header 'content-type: application/json' \
  --header 'x-b3-parentspanid: 3f55cb323a971bee' \
  --header 'x-b3-traceid: 3f55cb323a971b0c792caabcd31897cc' \
  --data '{"query":"{\n  resource_list(cursor: \"null\", types: [\"cf-application\"]) {\n    items {\n      ... on ResourceSummary {\n        crn\n        name\n        type\n        category\n        self_link {\n          uri\n        }\n        icon\n        description\n        created_at\n        updated_at\n        status\n        group\n        actions {\n          title\n          type\n        }\n        location\n        primaryIpAddress\n        primaryBackendIpAddress\n        tags\n      }\n    }\n    cursor\n  }\n}\n"}'
```

### What did you expect to see?
The trace id header should be present in the generated Zipkin record.

### What did you see instead?
A new trace id header is generated here: 
https://github.com/census-instrumentation/opencensus-node/blob/master/packages/opencensus-core/src/trace/model/tracer-base.ts#L118

### Additional context
Do I misunderstand the rules for this? I thought that an incoming request with:
 x-b3-traceid
 x-b3-spanid
would generate a new root element with the same trace id.

**Comment by jdbennet2001** [comment] 2019-05-30 20:51
Update. When I use `propagation.B3Format();` and set both traceid and spanid headers, then the trace id information is preserved but the generated span is not a 'root' span, which results in issues when I'm trying to maintain the parent / child relationship.

What am I doing wrong here?

**Comment by mayurkale22** [comment] 2019-05-30 21:09
Please use `x-b3-spanid` instead of `x-b3-parentspanid` while passing the headers. There is no really meaning of `x-b3-parentspanid` header. 

I tried locally and it is working for me.

```
curl --request GET 
--url http://localhost:3000/ping 
--header 'x-b3-traceid: 8ca46a5811634e08924ddd44cc91a31a' 
--header 'x-b3-spanid: d4c25dd1b2b47b45'
```

```
const tracing = require('@opencensus/nodejs');
const propagation = require('@opencensus/propagation-b3');
const zipkin = require('@opencensus/exporter-zipkin');

const exporter = new zipkin.ZipkinTraceExporter({
  url: 'http://localhost:9411/api/v2/spans',
  serviceName: 'test'
})

const tracer = tracing.start({
  propagation: new propagation.B3Format(),
  samplingRate: 1.0,
  bufferSize: 1,
  bufferTimeout: 1,
  logLevel: 4,
  exporter: exporter
}).tracer;

const express = require("express");
const app = express();

app.get('/ping', (_req, res) =>  {
  res.send('pong');
});

app.listen(3000, () => {
  console.log("App listening on 3000");
});
```

**Comment by jdbennet2001** [comment] 2019-05-30 22:00
I've been doing some more digging. If the trace and span ids are passed in, then they are recorded in the request record. However, there is no root span. 

So: tracer.currentRootSpan is undefined.

**Comment by jdbennet2001** [comment] 2019-05-30 22:15
Okay, found it. 

The incoming request generates a new span, but when the span is started at:
https://github.com/census-instrumentation/opencensus-node/blob/master/packages/opencensus-core/src/trace/model/span.ts#L313

which is:
```
    if (!this.parentSpanId) {
      this.tracer.setCurrentRootSpan(this);
    }
```
which prevents the root span from being set as the correct span, and propagating all information.

**Comment by jdbennet2001** [comment] 2019-05-31 13:53
Here's a better example, that I'm digging into:

```
curl --request GET \
  --url http://localhost:2808/one \
  --header 'x-b3-spanid: 3f55cb323a971bee' \
  --header 'x-b3-traceid: 3f55cb323a971b0c792caabcd31897cc'
```

```
const express = require('express')
const util    = require('util');
const rp 	  = require('request-promise');


const tracing       = require('@opencensus/nodejs');
const propagation   = require('@opencensus/propagation-b3');
const zipkin        = require('@opencensus/exporter-zipkin');

const exporter = new zipkin.ZipkinTraceExporter({
  url: 'http://localhost:9411/api/v2/spans',
  serviceName: 'test'
})

const b3 	= new propagation.B3Format();

const startOptions = {
  propagation: new propagation.B3Format(),
  samplingRate: 1.0,
  bufferSize: 1,
  bufferTimeout: 1,

  exporter
}

const tracer = tracing.start(startOptions).tracer;

const app 	  = express()
const port 	  = 2808


app.get('/one', function(req, res){
    debugger;
    console.log( `Headers (one): ${util.inspect(req.headers, {depth:null})}`);
    rp(`http://localhost:${port}/two`).then(data =>{
    	res.json(data);
    })
});

 app.get('/two', function(req, res){
    console.log( `Headers (two): ${util.inspect(req.headers, {depth:null})}`);
    rp(`http://localhost:${port}/three`).then(data =>{
    	res.json(data);
    }) 
});

 app.get('/three', function(req, res){
    console.log( `Headers (three): ${util.inspect(req.headers, {depth:null})}`);
    res.json('Hello World')
});

app.listen(port, () => console.log(`Example app listening on port ${port}!`))

```
Which produces:

```
Example app listening on port 2808!
Headers (one): { host: 'localhost:2808',
  'user-agent': 'insomnia/6.5.4',
  'x-b3-spanid': '3f55cb323a971bee',
  'x-b3-traceid': '3f55cb323a971b0c792caabcd31897cc',
  accept: '*/*' }
Headers (two): { host: 'localhost:2808', connection: 'close' }
Headers (three): { host: 'localhost:2808', connection: 'close' }
```

**Comment by jdbennet2001** [comment] 2019-05-31 14:56
Redoing my example:

curl:
```
curl --request GET \
  --url http://localhost:3000/users \
  --header 'x-b3-spanid: 896a13c2992d9653' \
  --header 'x-b3-traceid: 7cfcd1756c36421682cffb28fff36898'
```

code:
```
'use strict';

const express = require('express');
const path = require('path');
const cookieParser = require('cookie-parser');
const tracing = require('@opencensus/nodejs');
const propagation = require('@opencensus/propagation-b3');


const rp          = require('request-promise');

const b3 = new propagation.B3Format();

const startOptions = {propagation: b3};

const tracer = tracing.start(startOptions).tracer;

const port  = 3000;

const app = express();
 app.use(express.json());
app.use(express.urlencoded({ extended: false }));
app.use(cookieParser());
app.use(express.static(path.join(__dirname, 'public')));


app.get('/users', function(req, res){
  console.log( `user headers: ${JSON.stringify(req.headers)}`);
  rp('http://localhost:3000/sample').then(data =>{
    res.send(data);
  }, err =>{
    console.error( `${err.message}`);
  });
  
});

app.get('/sample', function(req, res){
  console.log( `sample headers: ${JSON.stringify(req.headers)}`);
  rp('https://jsonplaceholder.typicode.com/todos/1').then(data =>{
    res.send(data);
  });
  
});

var http = require('http');
app.set('port', port);
var server = http.createServer(app);
    server.listen(port);
module.exports = app;
```

Results: OpenCensus 0.0.13:
```
jonathans-mbp:tony-poc jdbennet@ca.ibm.com$ node app.js 
user headers: {"host":"localhost:3000","user-agent":"insomnia/6.5.4","x-b3-traceid":"7cfcd1756c36421682cffb28fff36898","x-b3-spanid":"896a13c2992d9653","accept":"*/*"}
sample headers: {"host":"localhost:3000","x-b3-traceid":"5364cd05dda34d48b98e876cf48e9902","x-b3-spanid":"4fac2a412f6c7b7d","x-b3-sampled":"1","connection":"close"}
RootSpan: {traceId: 873c763bde094480aec2fcbf26b88003, spanId: 8f63a93ba5f2844d, name: GET /todos/1 }
	ChildSpans:

RootSpan: {traceId: 5364cd05dda34d48b98e876cf48e9902, spanId: 3972c78d95fa29d5, name: /sample }
	ChildSpans:

RootSpan: {traceId: 5364cd05dda34d48b98e876cf48e9902, spanId: 4fac2a412f6c7b7d, name: GET /sample }
	ChildSpans:

RootSpan: {traceId: 7cfcd1756c36421682cffb28fff36898, spanId: 6f95f94465d7215a, name: /users }
	ChildSpans:
```

Note that there are _two_ trace id values.

Sample output: OpenCensus 0.0.11
```
jonathans-mbp:tony-poc jdbennet@ca.ibm.com$ node app.js 
user headers: {"host":"localhost:3000","user-agent":"insomnia/6.5.4","x-b3-traceid":"7cfcd1756c36421682cffb28fff36898","x-b3-spanid":"896a13c2992d9653","accept":"*/*"}
sample headers: {"host":"localhost:3000","x-b3-traceid":"7cfcd1756c36421682cffb28fff36898","x-b3-spanid":"944e7c5dd7521e18","x-b3-sampled":"1","connection":"close"}
RootSpan: {traceId: 7cfcd1756c36421682cffb28fff36898, spanId: 8fe1d92f86c8cda4, name: /sample }
	ChildSpans:
		{spanId: 1ca17be3e8222a03, name: GET /todos/1}
RootSpan: {traceId: 7cfcd1756c36421682cffb28fff36898, spanId: 0c65698dcf68733e, name: /users }
	ChildSpans:
		{spanId: 944e7c5dd7521e18, name: GET /sample}
```

Now there is, correctly, _one_ traceid.

**Comment by jdbennet2001** [comment] 2019-05-31 14:56
@mayurkale22 Does help explain the issue better?

**Comment by mayurkale22** [comment] 2019-05-31 19:31
@jdbennet2001 thanks for the sharing the example. I will give it a try today. Meantime, if you find the root cause or know the fix. Please feel free to open the PR.

**Comment by mayurkale22** [comment] 2019-06-01 05:22
@jdbennet2001 I managed to repro-d the issue, please review #570 for the fix.

Results after the fix:
```
RootSpan: {traceId: 6584887072f44a849a8f61f575ada60e, spanId: ebaa6b9b4ddd9c85, name: /sample }
	ChildSpans:

RootSpan: {traceId: 6584887072f44a849a8f61f575ada60e, spanId: 52d2c867d604272b, name: /users }
	ChildSpans:
		{spanId: a831522cd67c23ce, name: GET /sample}
```

**Comment by jdbennet2001** [comment] 2019-06-01 22:34
Thanks! I think the fix look good. Please let me know when there will be a 0.0.14 release so I can try it in our test system.

**Comment by mayurkale22** [comment] 2019-06-04 18:27
Closing the issue based on https://github.com/census-instrumentation/opencensus-node/pull/571#issuecomment-498762677.

**Closed by mayurkale22** 2019-06-04 18:27 UTC
Labels: P0, bug
